# **Weld Data**

In [ ]:
import pandas as pd

In [ ]:
df1= pd.read_excel("Weld Fracture_IR_Since_01-01-2015.xlsx")
df1.columns
filtered_df1= df1[df1["RLYCODE"]=="NCR"]
filtered_df1["DATE_OF_WELDING"]=pd.to_datetime(filtered_df1["DATE_OF_WELDING"], dayfirst=True, errors="coerce")
filtered_df1["FRACTURE_DATE"]=pd.to_datetime(filtered_df1["FRACTURE_DATE"], dayfirst=True, errors="coerce")
filtered_df1= filtered_df1.drop(columns="TIME_OF_DETECTION")
filtered_df1=filtered_df1.drop(columns="RLYCODE")
filtered_df1["DIVCODE"].unique()
len(filtered_df1.columns)

/tmp/ipykernel_3660/3409217457.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1["DATE_OF_WELDING"]=pd.to_datetime(filtered_df1["DATE_OF_WELDING"], dayfirst=True, errors="coerce")
/tmp/ipykernel_3660/3409217457.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1["FRACTURE_DATE"]=pd.to_datetime(filtered_df1["FRACTURE_DATE"], dayfirst=True, errors="coerce")

15

In [ ]:
filtered_df1.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'LR_RR', 'KM', 'MET', 'TYPE_OF_WELD',
       'RAIL_SECTION', 'DATE_OF_WELDING', 'ANNUAL_GMT', 'SPEED', 'GMT_CARRIED',
       'USFD_CLASSIFICATION', 'AXLE_LOAD', 'FRACTURE_DATE'],
      dtype='object')

In [ ]:
mapping = {
    'UP': 'Main_Run',
    'DN': 'Main_Run',
    'SL': 'Main_Run',
    'S':  'Main_Run',
    'IIIrd Line': 'Multi_Run'
}

filtered_df1['LINE'] = filtered_df1['LINE'].map(mapping).fillna('Non_Main')

In [ ]:
filtered_df1['LINE'].value_counts()

LINE
Main_Run     603
Multi_Run      7
Name: count, dtype: int64

In [ ]:
mapping = {
    'GW': 'GW',
    'DFWO': 'DFW',
    'DFWO Joggled Plate': 'DFW',
    'DFWR': 'DFW',
    'DFWR Joggled Plate': 'DFW',
    'DFW Joggled Plate': 'DFW',
    'OBS(W) Joggled Plate': 'OBS',
    'OBS(W)': 'OBS'
}

filtered_df1['USFD_CLASSIFICATION'] = filtered_df1['USFD_CLASSIFICATION'].map(mapping)

In [ ]:
filtered_df1["USFD_CLASSIFICATION"].unique()

array(['GW', 'DFW', 'OBS'], dtype=object)

In [ ]:
df_AGRA= pd.read_excel("Weld_Master_NCR_AGRA_AsOn_30_09_2025.xlsx")
df_PRYJ= pd.read_excel("Weld_Master_NCR_PRYJ_AsOn_30_09_2025.xlsx")
df_JHS= pd.read_excel("Weld_Master_NCR_JHS_AsOn_30_09_2025.xlsx")

df2= pd.concat([df_AGRA,df_PRYJ,df_JHS], ignore_index= True)

In [ ]:
filtered_df2=df2.drop(columns=["RLYCODE"])

In [ ]:
filtered_df2["USFD_CLASSIFICATION"].unique()

array(['DFWO(JP)', 'GW', 'OBS(W)(JP)', 'DFWR(JP)', 'DFWN', 'DFW(JP)'],
      dtype=object)

In [ ]:
filtered_df2=filtered_df2.rename(columns={"LRRR": "LR_RR"})

In [ ]:
mapping = {
    'GW': 'GW',
    'DFWO(JP)': 'DFW',
    'DFWR(JP)': 'DFW',
    'DFWN': 'DFW',
    'DFW(JP)': 'DFW',
    'OBS(W)(JP)': 'OBS'
}

filtered_df2['USFD_CLASSIFICATION'] = filtered_df2['USFD_CLASSIFICATION'].map(mapping)

In [ ]:
mapping = {
    'SL':           'Main_Run',
    'S':            'Main_Run',
    'UP':           'Main_Run',
    'DN':           'Main_Run',
    'IIIrd Line':   'Multi_Run',
    'IVth Line':    'Multi_Run',
    'A Line':       'Multi_Run',
    'MID':          'Non_Main',
    'N':            'Non_Main',
    'OML':          'Non_Main',
    'Chord Line':   'Non_Main',
    'Yard':         'Non_Main'
}

filtered_df2['LINE'] = filtered_df2['LINE'].map(mapping).fillna('Non_Main')

In [ ]:
filtered_df2["USFD_CLASSIFICATION"].unique()

array(['DFW', 'GW', 'OBS'], dtype=object)

In [ ]:
filtered_df2.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'LR_RR', 'KM', 'MET', 'TYPE_OF_WELD',
       'RAIL_SECTION', 'DATE_OF_WELDING', 'ANNUAL_GMT', 'SPEED', 'GMT_CARRIED',
       'USFD_CLASSIFICATION', 'AXLE_LOAD'],
      dtype='object')

In [ ]:
filtered_df1.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'LR_RR', 'KM', 'MET', 'TYPE_OF_WELD',
       'RAIL_SECTION', 'DATE_OF_WELDING', 'ANNUAL_GMT', 'SPEED', 'GMT_CARRIED',
       'USFD_CLASSIFICATION', 'AXLE_LOAD', 'FRACTURE_DATE'],
      dtype='object')

In [ ]:
filtered_df1["AXLE_LOAD"]=pd.to_numeric(filtered_df1["AXLE_LOAD"], errors="coerce")

In [ ]:
final_df= pd.concat([filtered_df1,filtered_df2], ignore_index= True)

In [ ]:
final_df

,DIVCODE,SECTION,LINE,LR_RR,KM,MET,TYPE_OF_WELD,RAIL_SECTION,DATE_OF_WELDING,ANNUAL_GMT,SPEED,GMT_CARRIED,USFD_CLASSIFICATION,AXLE_LOAD,FRACTURE_DATE
0,AGRA,AF-AH,Main_Run,RR,24,769.65,NAT,52KG,2016-05-09 00:00:00,25.244,110.0,311.049,GW,22.90,2025-02-25
1,AGRA,AGC-BKI connectivity line,Main_Run,RR,1344,683.95,AT,52KG,2015-01-01 00:00:00,3.330,15.0,13.409,DFW,22.90,2023-02-03
2,AGRA,AH-BTE,Main_Run,LR,26,398.50,AT,52KG,2010-12-13 00:00:00,31.140,110.0,117.840,GW,22.90,2017-01-28
3,AGRA,AH-BTE,Main_Run,LR,36,232.00,AT,52KG,2016-06-15 00:00:00,38.140,110.0,168.946,DFW,22.90,2021-11-21
4,AGRA,AH-BTE,Main_Run,LR,36,266.24,AT,52KG,2005-01-01 00:00:00,23.100,110.0,142.490,DFW,22.90,2015-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481929,JHS,OHAN MKP,Main_Run,RR,1417,208.60,AT,60KG,14/10/2023,10.291,100.0,19.577,GW,22.32,NaT
481930,JHS,OHAN MKP,Main_Run,RR,1417,234.60,AT,60KG,14/10/2023,10.291,100.0,19.577,GW,22.32,NaT
481931,JHS,OHAN MKP,Main_Run,RR,1417,364.70,NAT,60KG,08/10/2023,10.291,100.0,19.724,GW,22.32,NaT
481932,JHS,OHAN MKP,Main_Run,RR,1417,464.70,AT,60KG,08/10/2023,10.291,100.0,19.724,GW,22.32,NaT
481933,JHS,OHAN MKP,Main_Run,RR,1417,470.85,AT,60KG,09/10/2023,10.291,100.0,19.699,GW,22.32,NaT

In [ ]:
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold

# ---------------------
# 1) Column sets
# ---------------------
ohe_cols = ["DIVCODE", "LINE", "LR_RR", "TYPE_OF_WELD", "USFD_CLASSIFICATION", "RAIL_SECTION"]
num_cols = ["AXLE_LOAD", "GMT_CARRIED", "ANNUAL_GMT", "SPEED", "KM", "MET"]
start_col = "DATE_OF_WELDING"
end_col   = "FRACTURE_DATE"
section_col = "SECTION"           # entity encoding column

# ---------------------
# 2) Small transformers
# ---------------------
class AddEventFlag(BaseEstimator, TransformerMixin):
    """event = 1 if end date present, else 0."""
    def __init__(self, fracture_col=end_col):
        self.fracture_col = fracture_col
    def fit(self, X, y=None): return self
    def transform(self, X):
        X_ = X.copy()
        X_["event"] = np.where(pd.to_datetime(X_[self.fracture_col], errors="coerce").notna(), 1, 0)
        return X_

class DurationCalculator(BaseEstimator, TransformerMixin):
    """DURATION = (end - start).days; drops the two date cols."""
    def __init__(self, start_col=start_col, end_col=end_col, dayfirst=True):
        self.start_col, self.end_col, self.dayfirst = start_col, end_col, dayfirst
    def fit(self, X, y=None): return self
    def transform(self, X):
        X_ = X.copy()
        start = pd.to_datetime(X_[self.start_col], dayfirst=self.dayfirst, errors="coerce")
        end   = pd.to_datetime(X_[self.end_col],   dayfirst=self.dayfirst, errors="coerce")
        X_["DURATION"] = (end - start).dt.days
        X_.drop(columns=[self.start_col, self.end_col], inplace=True)
        return X_

class KFoldTargetEncoder(BaseEstimator, TransformerMixin):
    """OOF mean encoding for a single categorical column (SECTION)."""
    def __init__(self, col=section_col, n_splits=5, noise=0.0, random_state=42):
        self.col, self.n_splits, self.noise, self.random_state = col, n_splits, noise, random_state
    def fit(self, X, y):
        s = X[self.col].astype("category")
        self.global_mean_ = float(np.nanmean(y))
        self.cat_mean_ = pd.DataFrame({self.col: s, "_y": y}).groupby(self.col)["_y"].mean()
        return self
    def transform(self, X):
        s = X[self.col].astype("category")
        enc = s.map(self.cat_mean_).astype("float64").fillna(self.global_mean_)
        if self.noise > 0:
            enc = enc + np.random.RandomState(self.random_state).normal(0, self.noise, size=len(enc))
        return enc.to_numpy().reshape(-1, 1)
    def fit_transform(self, X, y):
        s = X[self.col].astype("category")
        kf = KFold(n_splits=self.n_splits, shuffle=True, random_state=self.random_state)
        oof = pd.Series(index=X.index, dtype="float64")
        y_arr = np.asarray(y)
        for tr, va in kf.split(X):
            means = pd.DataFrame({self.col: s.iloc[tr], "_y": y_arr[tr]}).groupby(self.col)["_y"].mean()
            oof.iloc[va] = s.iloc[va].map(means).astype("float64").fillna(float(np.nanmean(y_arr[tr])))
        self.fit(X, y)  # set full-data stats for inference
        if self.noise > 0:
            oof = oof + np.random.RandomState(self.random_state).normal(0, self.noise, size=len(oof))
        return oof.to_numpy().reshape(-1, 1)

class AddSectionEncoded(BaseEstimator, TransformerMixin):
    """Adds SECTION_ENC numeric column using target encoder."""
    def __init__(self, encoder: KFoldTargetEncoder):
        self.encoder = encoder
    def fit(self, X, y):
        self.encoder.fit(X, y)  # uses target y for mean encoding
        return self
    def transform(self, X):
        X_ = X.copy()
        X_["SECTION_ENC"] = self.encoder.transform(X)
        return X_

# ---------------------
# 3) ColumnTransformer for features
# ---------------------
if sklearn.__version__ >= "1.2":
    ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
else:
    ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse=False)
num_tf  = StandardScaler()

feature_ct = ColumnTransformer(
    transformers=[
        ("ohe",   ohe_tf,  ohe_cols),
        ("num",   num_tf,  num_cols),
        ("sec",   "passthrough", ["SECTION_ENC"])
    ],
    remainder="drop"
)

# ---------------------
# 4) Master preprocessing pipeline (no estimator)
# ---------------------
preprocess_pipeline = Pipeline(steps=[
    ("add_event",       AddEventFlag(fracture_col=end_col)),
    ("add_duration",    DurationCalculator(start_col=start_col, end_col=end_col, dayfirst=True)),
    ("add_section_enc", AddSectionEncoded(KFoldTargetEncoder(col=section_col))),
    ("features",        feature_ct),        # outputs X only (features + DURATION); event is not included here
])

# ---------------------
# 5) Usage
# ---------------------
# final_df: your concatenated dataframe (failures + non-failures).
# y_event and y_time should be taken from an intermediate copy to avoid mixing into features.

def prepare_survival_tensors(final_df: pd.DataFrame):
    """Returns X (features), y_time (duration), y_event, and the fitted preprocessing pipeline."""
    # compute event/duration in a side copy (mirrors pipeline steps)
    tmp = final_df.copy()
    tmp["event"] = np.where(pd.to_datetime(tmp[end_col], errors="coerce").notna(), 1, 0)
    start = pd.to_datetime(tmp[start_col], dayfirst=True, errors="coerce")
    end   = pd.to_datetime(tmp[end_col],   dayfirst=True, errors="coerce")
    tmp["DURATION"] = (end - start).dt.days

    y_event = tmp["event"].to_numpy().astype(int)
    y_time  = tmp["DURATION"].to_numpy().astype(float)

    # Fit-transform features (target encoder needs a target; use y_event)
    X = preprocess_pipeline.fit_transform(final_df, y_event)

    return X, y_time, y_event, preprocess_pipeline

# Example:
# X, y_time, y_event, pp = prepare_survival_tensors(final_df)
# -> feed (X, y_time, y_event) to your Cox-BNN training code.

In [ ]:
final_df.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'LR_RR', 'KM', 'MET', 'TYPE_OF_WELD',
       'RAIL_SECTION', 'DATE_OF_WELDING', 'ANNUAL_GMT', 'SPEED', 'GMT_CARRIED',
       'USFD_CLASSIFICATION', 'AXLE_LOAD', 'FRACTURE_DATE'],
      dtype='object')

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from scipy.optimize import minimize
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer


# =====================================================
# 1. COLUMN DEFINITIONS
# =====================================================

ohe_cols = [
    "DIVCODE",
    "LINE",
    "LR_RR",
    "TYPE_OF_WELD",
    "USFD_CLASSIFICATION",
    "RAIL_SECTION"
]

num_cols = [
    "AXLE_LOAD",
    "GMT_CARRIED",
    "ANNUAL_GMT",
    "SPEED",
    "KM",
    "MET"
]

section_col = "SECTION"
start_col = "DATE_OF_WELDING"
event_col = "FRACTURE_DATE"


# =====================================================
# 2. PREPROCESS FUNCTION
# =====================================================

def prepare_survival_data(df):

    df = df.copy()

    # ---- parse dates
    start = pd.to_datetime(df[start_col], errors="coerce", dayfirst=True)
    fracture = pd.to_datetime(df[event_col], errors="coerce", dayfirst=True)

    # ---- event indicator
    df["event"] = fracture.notna().astype(int)

# ---- duration for fractured rows
    duration_event = (fracture - start).dt.days

# ---- administrative censoring time (dataset end)
    admin_censor_date = fracture.max()

# ---- duration for censored rows
    duration_censor = (admin_censor_date - start).dt.days

# ---- assign duration
    df["DURATION"] = duration_event
    df.loc[df["event"] == 0, "DURATION"] = duration_censor[df["event"] == 0]

    # ---- remove invalid rows
    mask = (
        start.notna()
        & df["DURATION"].notna()
        & (df["DURATION"] >= 0)
    )

    df = df.loc[mask].copy()

    # ---- SECTION frequency encoding
    freq_map = df[section_col].value_counts(normalize=True).to_dict()

    df["SECTION_FREQ"] = (
        df[section_col]
        .map(freq_map)
        .fillna(0)
    )

    # ---- feature matrix
    feature_cols = ohe_cols + num_cols + ["SECTION_FREQ"]

    X_input = df[feature_cols].copy()

    # ---- encoders
    if sklearn.__version__ >= "1.2":
        ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    else:
        ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse=False)

    num_tf = StandardScaler()

    feature_ct = ColumnTransformer(
        transformers=[
            ("ohe", ohe_tf, ohe_cols),
            ("num", num_tf, num_cols),
            ("sec", "passthrough", ["SECTION_FREQ"])
        ],
        remainder="drop"
    )

    X = feature_ct.fit_transform(X_input)

    feature_names = feature_ct.get_feature_names_out()

    X_df = pd.DataFrame(X, columns=feature_names)

    # ---- targets
    T = df["DURATION"].to_numpy(dtype=float)
    E = df["event"].to_numpy(dtype=int)

    # ---- final checks
    mask = (
        np.isfinite(T)
        & np.isfinite(E)
        & np.all(np.isfinite(X), axis=1)
    )

    X_df = X_df.loc[mask]
    X = X[mask]
    T = T[mask]
    E = E[mask]

    # ---- breaks
    breaks = np.quantile(T, np.linspace(0, 1, 11))
    breaks[0] = 0.0
    breaks = np.unique(breaks)

    if breaks[-1] < np.max(T):
        breaks = np.append(breaks, np.max(T))

    return X_df, X, T, E, breaks

X_df, X, T, E, breaks = prepare_survival_data(final_df)

In [ ]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.30.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.18.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.17.0)
Downloading lifelines-0.30.3-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 23.2 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 15.1 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=7e04eac1d31269f5b0b106302590d34ad5deba166299d63f4e90588fc63ab94d
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd-gamma, formulaic, lifelines
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.3

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

tf.keras.backend.set_floatx("float32")
tfd = tfp.distributions


# ============================================================
# 0) START FROM CURRENT PREPROCESSED OBJECTS
#    Assumes these already exist:
#    X_df, X, T, E = prepare_survival_data(final_df)
# ============================================================

# Safety: rebuild aligned dataframe-like container from current outputs
dfv = pd.DataFrame(X, columns=X_df.columns)
dfv["time"] = T
dfv["event"] = E

# Filter exactly like rail pipeline style
dfv = dfv[dfv["time"].notna()].copy()
dfv = dfv[dfv["time"] > 0].copy()
dfv = dfv[dfv["event"].notna()].copy()

# Rebuild X, T, E from filtered dfv
T = dfv["time"].to_numpy(np.float32)
E = dfv["event"].astype(int).to_numpy(np.int32)

X_df_filtered = dfv.drop(columns=["time", "event"], errors="ignore").copy()
X = X_df_filtered.to_numpy(np.float32)

print("Final aligned shapes:", X.shape, T.shape, E.shape)
print("NaNs in T:", np.isnan(T).sum())
print("Min T:", float(np.nanmin(T)))
print("Event distribution:", np.unique(E, return_counts=True))

assert np.isnan(T).sum() == 0
assert float(np.min(T)) > 0
assert X.shape[0] == len(T) == len(E)


# ============================================================
# 1) TRAIN/TEST SPLIT
# ============================================================

X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X,
    T,
    E,
    test_size=0.2,
    random_state=42,
    stratify=E
)

print("Train X shape:", X_train.shape, "| Test X shape:", X_test.shape)
print("Train event distribution:", np.unique(y_event_tr, return_counts=True))
print("Test event distribution:", np.unique(y_event_te, return_counts=True))

assert set(np.unique(y_event_te)) == {0, 1}, "Test set missing a class!"


# ============================================================
# 2) SCALE FEATURES FOR BNN STABILITY
#    Same spirit as rail Cox-BNN pipeline
# ============================================================

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train).astype(np.float32)
X_test_s = scaler.transform(X_test).astype(np.float32)

print("NaN count in X_train_s:", np.isnan(X_train_s).sum())
print("NaN count in y_time_tr:", np.isnan(y_time_tr).sum())
print("NaN count in y_event_tr:", np.isnan(y_event_tr).sum())
print("Rows in X_train_s with at least one NaN:", np.isnan(X_train_s).any(axis=1).sum())

assert np.isnan(X_train_s).sum() == 0
assert np.isnan(X_test_s).sum() == 0


# ============================================================
# 3) TIMER CALLBACK
# ============================================================

class EpochTimer(keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        self.global_start = time.time()
        print("\nTraining started...\n")

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_start = time.time()

    def on_epoch_end(self, epoch, logs=None):
        epoch_time = time.time() - self.epoch_start
        total_time = time.time() - self.global_start
        loss = logs.get("loss", float("nan"))
        val_loss = logs.get("val_loss", float("nan"))

        print(
            f"Epoch {epoch+1:03d} | "
            f"loss={loss:.4f} | "
            f"val_loss={val_loss:.4f} | "
            f"epoch_time={epoch_time:.2f}s | "
            f"total_time={total_time/60:.2f} min"
        )

    def on_train_end(self, logs=None):
        total_time = time.time() - self.global_start
        print(f"\nTraining finished in {total_time/60:.2f} minutes.\n")


# ============================================================
# 4) BAYESIAN BNN PIECES
# ============================================================

def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )

posterior_fn = tfp.layers.default_mean_field_normal_fn(
    is_singular=False,
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)
)

def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))


# ============================================================
# 5) BUILD BNN
# ============================================================

def build_bnn(input_dim: int):
    inputs = keras.Input(shape=(int(input_dim),), dtype="float32", name="x")

    x = tfp.layers.DenseReparameterization(
        64,
        activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(inputs)

    x = tfp.layers.DenseReparameterization(
        32,
        activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(x)

    outputs = tfp.layers.DenseReparameterization(
        1,
        activation=None,
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(x)

    return keras.Model(inputs, outputs, name="BNN_gX")


# ============================================================
# 6) COX PARTIAL LIKELIHOOD LOSS
#    Full-risk-set version, same style as rail pipeline
# ============================================================

@tf.function
def neg_log_partial_lik(y_true, y_pred):
    event = tf.cast(y_true[:, 0], tf.float32)
    time_ = tf.cast(y_true[:, 1], tf.float32)
    risk = tf.cast(tf.squeeze(y_pred, axis=-1), tf.float32)

    # sort by time descending
    order = tf.argsort(time_, direction="DESCENDING")
    time_ = tf.gather(time_, order)
    event = tf.gather(event, order)
    risk = tf.gather(risk, order)

    # prefix cumulative logsumexp
    lse_prefix = tf.math.cumulative_logsumexp(risk)

    # Breslow tie handling
    is_new = tf.concat([[True], tf.not_equal(time_[1:], time_[:-1])], axis=0)
    gid = tf.cumsum(tf.cast(is_new, tf.int32)) - 1

    is_end = tf.concat([tf.not_equal(time_[:-1], time_[1:]), [True]], axis=0)
    end_lse = tf.boolean_mask(lse_prefix, is_end)
    denom = tf.gather(end_lse, gid)

    loglik = tf.reduce_sum(event * (risk - denom))
    return -loglik / (tf.reduce_sum(event) + 1e-8)


# ============================================================
# 7) TRAIN BNN AND GET g(x)
#    Full batch because Cox loss depends on full risk sets
# ============================================================

def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te, lr=1e-3, epochs=100):
    model = build_bnn(X_tr.shape[1])
    model.compile(
        optimizer=keras.optimizers.RMSprop(lr),
        loss=neg_log_partial_lik
    )

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    es = keras.callbacks.EarlyStopping(
        patience=10,
        restore_best_weights=True
    )

    timer = EpochTimer()

    model.fit(
        X_tr.astype(np.float32),
        y_tr,
        batch_size=X_tr.shape[0],   # full batch is important here
        epochs=epochs,
        verbose=0,
        validation_split=0.2,
        shuffle=False,
        callbacks=[es, timer]
    )

    g_tr = model.predict(X_tr.astype(np.float32), verbose=0).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), verbose=0).reshape(-1)

    return g_tr, g_te


# ============================================================
# 8) TRAIN BNN NONLINEAR TERM
# ============================================================

g_tr, g_te = train_bnn_and_get_g(
    X_train_s,
    y_time_tr,
    y_event_tr,
    X_test_s,
    lr=1e-3,
    epochs=100
)


# ============================================================
# 9) HYBRID LINEAR COX PART
#    Use current weld feature names from X_df_filtered.columns
# ============================================================

feature_names = list(X_df_filtered.columns)

# ===============================
# Select treatment variables (SET 1)
# ===============================

#colnames = list(X_df.columns)   # must match the matrix used to build X
colnames = list(X_df_filtered.columns)

def find_col(name):
    matches = [i for i,c in enumerate(colnames) if name in c]
    if len(matches) == 0:
        raise ValueError(f"{name} not found")
    return matches[0]


idx_line  = find_col("ohe__LINE")
idx_lr    = find_col("ohe__LR_RR")
idx_weld  = find_col("ohe__TYPE_OF_WELD")
idx_rail  = find_col("ohe__RAIL_SECTION")
idx_usfd  = find_col("ohe__USFD_CLASSIFICATION")

idx_speed  = find_col("num__SPEED")
idx_annual = find_col("num__ANNUAL_GMT")
idx_gmt    = find_col("num__GMT_CARRIED")
idx_axle   = find_col("num__AXLE_LOAD")

treat_idx = [
    idx_line
    , idx_lr
    , idx_weld
    , idx_rail
    , idx_usfd
    , idx_speed
    , idx_annual
    , idx_gmt
    , idx_axle
]

X_lin_tr = X_train[:, treat_idx]
X_lin_te = X_test[:, treat_idx]

col_treat = [colnames[i] for i in treat_idx]

train_df = pd.DataFrame(X_lin_tr, columns=col_treat)
train_df["time"] = y_time_tr
train_df["event"] = y_event_tr
train_df["g_bnn"] = g_tr

test_df = pd.DataFrame(X_lin_te, columns=col_treat)
test_df["time"] = y_time_te
test_df["event"] = y_event_te
test_df["g_bnn"] = g_te

formula = " + ".join(col_treat) + " + g_bnn"


# ============================================================
# 10) FIT HYBRID COX MODEL
# ============================================================

cph = CoxPHFitter()
cph.fit(
    train_df,
    duration_col="time",
    event_col="event",
    formula=formula
)

print("\nCox coefficients:")
print(cph.params_)


# ============================================================
# 11) C-INDEX
# ============================================================

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(
    train_df["time"].values,
    -risk_tr,
    train_df["event"].values
)

c_te = concordance_index(
    test_df["time"].values,
    -risk_te,
    test_df["event"].values
)

print(f"\nC-index train = {c_tr:.3f}")
print(f"C-index test  = {c_te:.3f}")

Final aligned shapes: (472739, 23) (472739,) (472739,)
NaNs in T: 0
Min T: 1.0
Event distribution: (array([0, 1], dtype=int32), array([472132,    607]))
Train X shape: (378191, 23) | Test X shape: (94548, 23)
Train event distribution: (array([0, 1], dtype=int32), array([377705,    486]))
Test event distribution: (array([0, 1], dtype=int32), array([94427,   121]))
NaN count in X_train_s: 0
NaN count in y_time_tr: 0
NaN count in y_event_tr: 0
Rows in X_train_s with at least one NaN: 0

/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:99: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  loc = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:109: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  untransformed_scale = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(

Training started...

Epoch 001 | loss=12.0096 | val_loss=10.5597 | epoch_time=3.31s | total_time=0.06 min
Epoch 002 | loss=12.0697 | val_loss=10.7163 | epoch_time=0.07s | total_time=0.06 min
Epoch 003 | loss=12.0008 | val_loss=10.6197 | epoch_time=0.07s | total_time=0.06 min
Epoch 004 | loss=12.0610 | val_loss=10.4132 | epoch_time=0.09s | total_time=0.06 min
Epoch 005 | loss=12.0336 | val_loss=10.7392 | epoch_time=0.07s | total_time=0.06 min
Epoch 006 | loss=11.9193 | val_loss=10.6128 | epoch_time=0.07s | total_time=0.06 min
Epoch 007 | loss=12.0607 | val_loss=10.6489 | epoch_time=0.07s | total_time=0.06 min
Epoch 008 | loss=11.9225 | val_loss=10.7654 | epoch_time=0.07s | total_time=0.06 min
Epoch 009 | loss=12.0470 | val_loss=10.6625 | epoch_time=0.07s | total_time=0.07 min
Epoch 010 | loss=11.9883 | val_loss=10.6126 | epoch_time=0.08s | total_time=0.07 min
Epoch 011 | loss=12.1353 | val_loss=10.6336 | epoch_time=0.07s | total_time=0.07 min
Epoch 012 | loss=12.0438 | val_loss=10.6429 | epoch_time=0.08s | total_time=0.07 min
Epoch 013 | loss=12.1156 | val_loss=10.6441 | epoch_time=0.07s | total_time=0.07 min
Epoch 014 | loss=12.0353 | val_loss=10.6314 | epoch_time=0.07s | total_time=0.07 min

Training finished in 0.07 minutes.


Cox coefficients:
covariate
ohe__LINE_Main_Run              1.854483
ohe__LR_RR_LR                  -0.139741
ohe__TYPE_OF_WELD_AT            2.297063
ohe__RAIL_SECTION_52KG          2.838675
ohe__USFD_CLASSIFICATION_DFW    0.391044
num__SPEED                      1.551572
num__ANNUAL_GMT                 1.777912
num__GMT_CARRIED               -1.178100
num__AXLE_LOAD                 -0.787274
g_bnn                          -0.024012
Name: coef, dtype: float64

C-index train = 0.941
C-index test  = 0.949

In [ ]:
|print("Feature count:", len(X_df_filtered.columns))
print("Matrix width:", X_train.shape[1])

Feature count: 23
Matrix width: 23

In [ ]:
import numpy as np

# survival matrix already computed for IBS
# S_pred shape = (n_test, n_times)

times = times_ibs


def median_time_from_curve(times, s_row):

    idx = np.where(s_row <= 0.5)[0]

    if len(idx) == 0:
        return times[-1]

    return times[idx[0]]


# predicted median survival
t50_pred = np.array(
    [median_time_from_curve(times, s_row) for s_row in S_pred],
    dtype=float
)

# evaluate only on events
mask_event = (y_event_te == 1)

rmse = np.sqrt(
    np.mean(
        (t50_pred[mask_event] - y_time_te[mask_event]) ** 2
    )
)

print("RMSE (median survival time, events only):", float(rmse))
print("Num events used:", int(mask_event.sum()))

RMSE (median survival time, events only): 5666.431776116778
Num events used: 121

In [ ]:
!pip install scikit-survival

Collecting scikit-survival
  Downloading scikit_survival-0.27.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Collecting ecos (from scikit-survival)
  Downloading ecos-2.0.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.5.3)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.14.1)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.0.2)
Requirement already satisfied: osqp>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.1.1)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.2.2)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.16.3)
Collecting scikit-learn<1.9,>=1.8.0 (from scikit-survival)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from osqp>=1.0.2->scikit-survival) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from osqp>=1.0.2->scikit-survival) (75.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2025.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.9,>=1.8.0->scikit-survival) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->scikit-survival) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->osqp>=1.0.2->scikit-survival) (3.0.3)
Downloading scikit_survival-0.27.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 74.1 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 90.0 MB/s eta 0:00:00
Downloading ecos-2.0.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (222 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.1/222.1 kB 27.4 MB/s eta 0:00:00
Installing collected packages: scikit-learn, ecos, scikit-survival
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed ecos-2.0.14 scikit-learn-1.8.0 scikit-survival-0.27.0

In [ ]:
import numpy as np
from sksurv.metrics import integrated_brier_score
from sksurv.util import Surv

# structured arrays
y_train_struct = Surv.from_arrays(
    y_event_tr.astype(bool),
    y_time_tr.astype(float)
)

y_test_struct = Surv.from_arrays(
    y_event_te.astype(bool),
    y_time_te.astype(float)
)

# time grid (must lie within follow-up)
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)

times_ibs = np.linspace(t_min, eps, 200)

# predicted survival curves
surv_df = cph.predict_survival_function(test_df, times=times_ibs)

# convert to matrix
S_pred = surv_df.to_numpy().T   # (n_test, n_times)

# IBS
ibs = integrated_brier_score(
    y_train_struct,
    y_test_struct,
    S_pred,
    times_ibs
)

print("IBS:", float(ibs))

IBS: 0.0024993732593045293

In [ ]:
print("Min duration:", np.min(y_time_te))
print("Median duration:", np.median(y_time_te))
print("Max duration:", np.max(y_time_te))

Min duration: 1.0
Median duration: 2542.0
Max duration: 10236.0

# COX+**BNN**

In [ ]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.30.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.17.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.17.0)
Downloading lifelines-0.30.3-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 12.6 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 16.9 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=7d77b927dec3ee8adea24c909175bb4cd6d7aad734afa92abbc695ac4cd122f2
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd-gamma, formulaic, lifelines
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.3

In [ ]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
import time

tfd = tfp.distributions


# ================= Timer =================
class EpochTimer(keras.callbacks.Callback):

    def on_train_begin(self, logs=None):
        self.t0 = time.time()

    def on_epoch_begin(self, epoch, logs=None):
        self.e0 = time.time()
        print(f"\nEpoch {epoch+1} started...")

    def on_epoch_end(self, epoch, logs=None):
        dt = time.time() - self.e0
        total = (time.time() - self.t0) / 60
        print(
            f"Epoch {epoch+1} ended — {dt:.2f}s | "
            f"loss {logs['loss']:.4f} | val {logs['val_loss']:.4f} | "
            f"total {total:.1f} min"
        )


# ================= Bayesian Pieces =================

def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )


posterior_fn = tfp.layers.default_mean_field_normal_fn(
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)
)


def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))


# ================= Smaller BNN =================

def build_bnn(input_dim):

    inputs = keras.Input(shape=(input_dim,), dtype="float32")

    x = tfp.layers.DenseReparameterization(
        32, activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(inputs)

    x = tfp.layers.DenseReparameterization(
        16, activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(x)

    outputs = tfp.layers.DenseReparameterization(
        1,
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(x)

    return keras.Model(inputs, outputs)


# ================= Faster Cox Loss =================

@tf.function
def neg_log_partial_lik(y_true, y_pred):

    event = y_true[:, 0]
    risk = tf.squeeze(y_pred, axis=-1)

    # cumulative log-sum-exp
    log_cumsum = tf.math.log(
        tf.cumsum(tf.exp(risk), reverse=True) + 1e-12
    )

    loglik = tf.reduce_sum(event * (risk - log_cumsum))

    return -loglik / (tf.reduce_sum(event) + 1e-8)


# ================= Training =================

def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te):

    # ---- Sort once for Cox loss ----
    order = np.argsort(-time_tr)

    X_tr = X_tr[order]
    time_tr = time_tr[order]
    event_tr = event_tr[order]

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    # ---- Train/validation split ----
    n = X_tr.shape[0]
    split = int(n * 0.8)

    X_train = X_tr[:split]
    y_train = y_tr[:split]

    X_val = X_tr[split:]
    y_val = y_tr[split:]

    # ---- tf.data datasets ----
    train_ds = (
        tf.data.Dataset
        .from_tensor_slices((X_train.astype(np.float32), y_train))
        .shuffle(10000)
        .batch(4096)
        .prefetch(tf.data.AUTOTUNE)
    )

    val_ds = (
        tf.data.Dataset
        .from_tensor_slices((X_val.astype(np.float32), y_val))
        .batch(4096)
        .prefetch(tf.data.AUTOTUNE)
    )

    # ---- Model ----
    model = build_bnn(X_tr.shape[1])

    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss=neg_log_partial_lik
    )

    es = keras.callbacks.EarlyStopping(
        patience=5,
        restore_best_weights=True
    )

    timer = EpochTimer()

    # ---- Train ----
    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=30,
        callbacks=[es, timer],
        verbose=0
    )

    # ---- Predictions ----
    g_tr = model.predict(X_tr.astype(np.float32), batch_size=8192).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), batch_size=8192).reshape(-1)

    return g_tr, g_te

In [ ]:
!pip install tensorflow-probability

Requirement already satisfied: tensorflow-probability in /usr/local/lib/python3.12/dist-packages (0.25.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (1.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (1.17.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (2.0.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (4.4.2)
Requirement already satisfied: cloudpickle>=1.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (3.1.2)
Requirement already satisfied: gast>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (0.7.0)
Requirement already satisfied: dm-tree in /usr/local/lib/python3.12/dist-packages (from tensorflow-probability) (0.1.9)
Requirement already satisfied: attrs>=18.2.0 in /usr/local/lib/python3.12/dist-packages (from dm-tree->tensorflow-probability) (25.4.0)
Requirement already satisfied: wrapt>=1.11.2 in /usr/local/lib/python3.12/dist-packages (from dm-tree->tensorflow-probability) (2.1.2)

In [ ]:
import tensorflow_probability as tfp
tfd = tfp.distributions

In [ ]:
final_df.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'LR_RR', 'KM', 'MET', 'TYPE_OF_WELD',
       'RAIL_SECTION', 'DATE_OF_WELDING', 'ANNUAL_GMT', 'SPEED', 'GMT_CARRIED',
       'USFD_CLASSIFICATION', 'AXLE_LOAD', 'FRACTURE_DATE'],
      dtype='object')

In [ ]:
feature_names = pp.named_steps["features"].get_feature_names_out()
feature_names

array(['ohe__DIVCODE_AGRA', 'ohe__DIVCODE_JHS', 'ohe__DIVCODE_PRYJ',
       'ohe__LINE_Main_Run', 'ohe__LINE_Multi_Run', 'ohe__LINE_Non_Main',
       'ohe__LR_RR_LR', 'ohe__LR_RR_RR', 'ohe__TYPE_OF_WELD_AT',
       'ohe__TYPE_OF_WELD_NAT', 'ohe__USFD_CLASSIFICATION_DFW',
       'ohe__USFD_CLASSIFICATION_GW', 'ohe__USFD_CLASSIFICATION_OBS',
       'ohe__RAIL_SECTION_52KG', 'ohe__RAIL_SECTION_60KG',
       'ohe__RAIL_SECTION_OTHER', 'num__AXLE_LOAD', 'num__GMT_CARRIED',
       'num__ANNUAL_GMT', 'num__SPEED', 'num__KM', 'num__MET',
       'sec__SECTION_ENC'], dtype=object)

In [ ]:
# === BNN training ===
g_tr_sorted, g_te = train_bnn_and_get_g(
    X_train,
    y_time_tr,
    y_event_tr,
    X_test
)

# === restore original order (because BNN sorted by time) ===
order = np.argsort(-y_time_tr)
inv_order = np.argsort(order)

g_tr = g_tr_sorted[inv_order]


# ===============================
# Select linear Cox variables
# ===============================

import pandas as pd

feature_names = pp.named_steps["features"].get_feature_names_out()


def find_col(col_name):
    matches = [i for i, name in enumerate(feature_names) if col_name in name]
    if len(matches) == 0:
        raise ValueError(f"{col_name} not found in feature names")
    if len(matches) > 1:
        print(f"Warning: multiple matches for {col_name}, using first: {feature_names[matches[0]]}")
    return matches[0]


# === column indices ===
# indices
i_axle   = find_col("AXLE_LOAD")
i_gmt    = find_col("GMT_CARRIED")
i_annual = find_col("ANNUAL_GMT")

i_rail_52 = find_col("RAIL_SECTION_52KG")
i_rail_60 = find_col("RAIL_SECTION_60KG")
# drop OTHER to avoid singular matrix

X_lin_tr = X_train[:, [i_axle, i_gmt, i_annual, i_rail_52, i_rail_60]]
X_lin_te = X_test[:,  [i_axle, i_gmt, i_annual, i_rail_52, i_rail_60]]


train_df = pd.DataFrame({
    "time": y_time_tr,
    "event": y_event_tr,
    "AXLE_LOAD": X_lin_tr[:,0],
    "GMT_CARRIED": X_lin_tr[:,1],
    "ANNUAL_GMT": X_lin_tr[:,2],
    "RAIL_52KG": X_lin_tr[:,3],
    "RAIL_60KG": X_lin_tr[:,4],
    "g_bnn": g_tr
})

test_df = pd.DataFrame({
    "time": y_time_te,
    "event": y_event_te,
    "AXLE_LOAD": X_lin_te[:,0],
    "GMT_CARRIED": X_lin_te[:,1],
    "ANNUAL_GMT": X_lin_te[:,2],
    "RAIL_52KG": X_lin_te[:,3],
    "RAIL_60KG": X_lin_te[:,4],
    "g_bnn": g_te
})

# === Cox formula ===
formula = "AXLE_LOAD + GMT_CARRIED + ANNUAL_GMT + RAIL_52KG + RAIL_60KG + g_bnn"





# ===============================
# Fit Cox Model
# ===============================

from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

cph = CoxPHFitter()

cph.fit(
    train_df,
    duration_col="time",
    event_col="event",
    formula=formula
)


# ===============================
# Print coefficients
# ===============================

print("\nCox coefficients")
print(cph.params_)


# ===============================
# Compute C-index
# ===============================

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(
    train_df["time"].values,
    -risk_tr,
    train_df["event"].values
)

c_te = concordance_index(
    test_df["time"].values,
    -risk_te,
    test_df["event"].values
)

print(f"\nC-index train = {c_tr:.3f}")
print(f"C-index test  = {c_te:.3f}")

/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:99: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  loc = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:109: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  untransformed_scale = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(

Epoch 1 started...
Epoch 1 ended — 4.52s | loss 0.1256 | val 0.1909 | total 0.1 min

Epoch 2 started...
Epoch 2 ended — 1.06s | loss 0.1301 | val 0.1898 | total 0.1 min

Epoch 3 started...
Epoch 3 ended — 1.05s | loss 0.0950 | val 0.1899 | total 0.1 min

Epoch 4 started...
Epoch 4 ended — 1.05s | loss 0.1206 | val 0.1895 | total 0.1 min

Epoch 5 started...
Epoch 5 ended — 1.03s | loss 0.1013 | val 0.1891 | total 0.1 min

Epoch 6 started...
Epoch 6 ended — 1.05s | loss 0.1180 | val 0.1898 | total 0.2 min

Epoch 7 started...
Epoch 7 ended — 1.31s | loss 0.1313 | val 0.1888 | total 0.2 min

Epoch 8 started...
Epoch 8 ended — 1.70s | loss 0.1320 | val 0.1889 | total 0.2 min

Epoch 9 started...
Epoch 9 ended — 0.99s | loss 0.1253 | val 0.1888 | total 0.2 min

Epoch 10 started...
Epoch 10 ended — 1.05s | loss 0.1238 | val 0.1879 | total 0.2 min

Epoch 11 started...
Epoch 11 ended — 1.10s | loss 0.0941 | val 0.1881 | total 0.3 min

Epoch 12 started...
Epoch 12 ended — 1.06s | loss 0.1248 | val 0.1875 | total 0.3 min

Epoch 13 started...
Epoch 13 ended — 1.04s | loss 0.1220 | val 0.1881 | total 0.3 min

Epoch 14 started...
Epoch 14 ended — 1.08s | loss 0.1126 | val 0.1882 | total 0.3 min

Epoch 15 started...
Epoch 15 ended — 1.04s | loss 0.0976 | val 0.1878 | total 0.3 min

Epoch 16 started...
Epoch 16 ended — 1.03s | loss 0.1264 | val 0.1876 | total 0.4 min

Epoch 17 started...
Epoch 17 ended — 1.00s | loss 0.1075 | val 0.1874 | total 0.4 min

Epoch 18 started...
Epoch 18 ended — 1.45s | loss 0.1254 | val 0.1870 | total 0.4 min

Epoch 19 started...
Epoch 19 ended — 1.59s | loss 0.1050 | val 0.1874 | total 0.4 min

Epoch 20 started...
Epoch 20 ended — 1.04s | loss 0.0811 | val 0.1876 | total 0.4 min

Epoch 21 started...
Epoch 21 ended — 1.05s | loss 0.1277 | val 0.1875 | total 0.5 min

Epoch 22 started...
Epoch 22 ended — 1.07s | loss 0.1253 | val 0.1866 | total 0.5 min

Epoch 23 started...
Epoch 23 ended — 1.03s | loss 0.1081 | val 0.1875 | total 0.5 min

Epoch 24 started...
Epoch 24 ended — 1.03s | loss 0.0663 | val 0.1861 | total 0.5 min

Epoch 25 started...
Epoch 25 ended — 1.02s | loss 0.1154 | val 0.1881 | total 0.5 min

Epoch 26 started...
Epoch 26 ended — 1.04s | loss 0.1157 | val 0.1877 | total 0.5 min

Epoch 27 started...
Epoch 27 ended — 1.03s | loss 0.0677 | val 0.1925 | total 0.6 min

Epoch 28 started...
Epoch 28 ended — 1.07s | loss 0.0656 | val 0.2011 | total 0.6 min

Epoch 29 started...
Epoch 29 ended — 1.56s | loss 0.0596 | val 0.1910 | total 0.6 min
47/47 [==============================] - 0s 3ms/step
12/12 [==============================] - 0s 3ms/step

/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1789: RuntimeWarning: overflow encountered in exp
  scores = weights * exp(dot(X, beta))
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:52: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1852: RuntimeWarning: invalid value encountered in multiply
  a1 = risk_phi_x_x * denom
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1854: RuntimeWarning: invalid value encountered in multiply
  summand = numer * denom[:, None]
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1861: RuntimeWarning: divide by zero encountered in log
  log_lik = log_lik + dot(x_death_sum, beta) + weighted_average * log(denom).sum()
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1837: RuntimeWarning: invalid value encountered in multiply
  numer = risk_phi_x - multiply.outer(increasing_proportion, tie_phi_x)
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1837: RuntimeWarning: invalid value encountered in subtract
  numer = risk_phi_x - multiply.outer(increasing_proportion, tie_phi_x)
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1838: RuntimeWarning: invalid value encountered in multiply
  denom = 1.0 / (risk_phi - increasing_proportion * tie_phi)
/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1838: RuntimeWarning: invalid value encountered in subtract
  denom = 1.0 / (risk_phi - increasing_proportion * tie_phi)

ConvergenceError: Convergence halted due to matrix inversion problems. Suspicion is high collinearity. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-modelMatrix is singular.

In [ ]:
train_df["event"].value_counts()

event
0    385059
1       488
Name: count, dtype: int64

In [ ]:
np.isfinite(train_df["g_bnn"]).all()

np.False_

# ***RAIL DATA***

In [ ]:
import pandas as pd

In [ ]:
df_processed=pd.read_pickle("processed_df.pkl")

In [ ]:
len(df_processed.columns)

27

In [ ]:
import numpy as np

In [ ]:
df_processed.columns

Index(['DIVCODE', 'SECTION', 'LINE', 'RAIL_SECTION', 'ANNUAL_GMT', 'SPEED',
       'GMTCARRIED', 'USFDCLASSIFICATION', 'LRRR', 'AXLELOAD', 'TRACK_TYPE',
       'STRAIGHT_CURVE', 'SERVICE_LIFE', 'DURATION', 'Kilometerage',
       'FRACTURE_TIMESTAMP', 'LAYING_DATE', 'USFDTIMESTAMP'],
      dtype='object')

In [ ]:
drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP"
]

valid = (
    df_processed["num__DURATION"].notna() &
    (df_processed["num__DURATION"] > 0)
)

df = df_processed.loc[valid].copy()


X_df = df.drop(columns=drop_cols, errors="ignore")

X = X_df.to_numpy(np.float32)
T = df_processed["num__DURATION"].to_numpy(np.float32)
E = df_processed["num__Event"].to_numpy(np.int32)

In [ ]:
dfv = df_processed.copy()

dfv = dfv[dfv["num__DURATION"].notna()]
dfv = dfv[dfv["num__DURATION"] > 0]
dfv = dfv[dfv["num__Event"].notna()]

# NOW build everything from dfv

T = dfv["num__DURATION"].to_numpy(np.float32)
E = dfv["num__Event"].astype(int).to_numpy(np.int32)

drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP",
]

X_df = dfv.drop(columns=drop_cols, errors="ignore")
X = X_df.to_numpy(np.float32)

print(len(X), len(T), len(E))

550 550 550

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X,
    T,
    E,
    test_size=0.2,
    random_state=42,
    stratify=E
)

In [ ]:
valid_tr = (~np.isnan(y_time_tr)) & (y_time_tr > 0)
valid_te = (~np.isnan(y_time_te)) & (y_time_te > 0)

X_train = X_train[valid_tr]
y_time_tr = y_time_tr[valid_tr]
y_event_tr = y_event_tr[valid_tr]

X_test = X_test[valid_te]
y_time_te = y_time_te[valid_te]
y_event_te = y_event_te[valid_te]

In [ ]:
print(np.isnan(y_time_tr).sum(), y_time_tr.min())

0 1.0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

In [ ]:
import tensorflow as tf

print("GPU Available:", tf.config.list_physical_devices('GPU'))

GPU Available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.30.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.18.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.17.0)
Downloading lifelines-0.30.3-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 3.2 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 15.0 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=dd02d54c3e803636e873279d1c3601bf498f5bb4ba492c6e40e151d25eb3ab6e
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd-gamma, formulaic, lifelines
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.3

In [ ]:
df.columns

Index(['ord__RAIL_SECTION', 'ord__AXLELOAD', 'ohe__DIVCODE_HWH',
       'ohe__DIVCODE_MLDT', 'ohe__DIVCODE_SDAH', 'ohe__LINE_OTH',
       'ohe__LINE_SL', 'ohe__LINE_UP', 'ohe__USFDCLASSIFICATION_IMR',
       'ohe__USFDCLASSIFICATION_OBS',
       'ohe__USFDCLASSIFICATION_OBS Joggled Plate',
       'ohe__USFDCLASSIFICATION_OBSJP', 'ohe__LRRR_RR', 'ohe__TRACK_TYPE_LWR',
       'ohe__TRACK_TYPE_SWR', 'ohe__STRAIGHT_CURVE_STRAIGHT',
       'num__ANNUAL_GMT', 'num__SPEED', 'num__GMTCARRIED', 'num__SERVICE_LIFE',
       'num__DURATION', 'num__Kilometerage', 'num__Event',
       'date__FRACTURE_TIMESTAMP', 'date__LAYING_DATE', 'date__USFDTIMESTAMP',
       'SECTION_FREQ', 'CENSOR_DATE', 'DURATION'],
      dtype='object')

In [ ]:
df_processed.columns

Index(['ord__RAIL_SECTION', 'ord__AXLELOAD', 'ohe__DIVCODE_JHS',
       'ohe__DIVCODE_PRYJ', 'ohe__LINE_OTH', 'ohe__LINE_SL', 'ohe__LINE_UP',
       'ohe__USFDCLASSIFICATION_OBS',
       'ohe__USFDCLASSIFICATION_OBS Joggled Plate',
       'ohe__USFDCLASSIFICATION_OBSJP', 'ohe__LRRR_RR', 'ohe__TRACK_TYPE_LWR',
       'ohe__TRACK_TYPE_SWR', 'ohe__STRAIGHT_CURVE_STRAIGHT',
       'num__ANNUAL_GMT', 'num__SPEED', 'num__GMTCARRIED', 'num__SERVICE_LIFE',
       'num__DURATION', 'num__Kilometerage', 'num__Event',
       'date__FRACTURE_TIMESTAMP', 'date__LAYING_DATE', 'date__USFDTIMESTAMP',
       'SECTION_FREQ', 'CENSOR_DATE', 'DURATION'],
      dtype='object')

In [ ]:
import numpy as np, pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import time
tf.keras.backend.set_floatx('float32')

# =========================
# 0) MUST: define tfd
# =========================
tfd = tfp.distributions

# =========================
# 1) Timer callback
# =========================
class EpochTimer(keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        self.global_start = time.time()
        print("\nTraining started...\n")

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_start = time.time()

    def on_epoch_end(self, epoch, logs=None):
        epoch_time = time.time() - self.epoch_start
        total_time = time.time() - self.global_start
        loss = logs.get("loss", float("nan"))
        val_loss = logs.get("val_loss", float("nan"))

        print(
            f"Epoch {epoch+1:03d} | "
            f"loss={loss:.4f} | "
            f"val_loss={val_loss:.4f} | "
            f"epoch_time={epoch_time:.2f}s | "
            f"total_time={total_time/60:.2f} min"
        )

    def on_train_end(self, logs=None):
        total_time = time.time() - self.global_start
        print(f"\nTraining finished in {total_time/60:.2f} minutes.\n")

# =========================
# 2) BNN priors/posteriors
# =========================
def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )

posterior_fn = tfp.layers.default_mean_field_normal_fn(
    is_singular=False,
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)  # ~ std 0.1 after softplus
)

def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))

def build_bnn(input_dim: int):
    inputs = keras.Input(shape=(int(input_dim),), dtype="float32", name="x")
    x = tfp.layers.DenseReparameterization(
        64, activation="relu",
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(inputs)
    x = tfp.layers.DenseReparameterization(
        32, activation="relu",
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(x)
    outputs = tfp.layers.DenseReparameterization(
        1, activation=None,
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(x)
    return keras.Model(inputs, outputs, name="BNN_gX")

# =========================
# 3) FIXED Cox partial likelihood loss
#    - full risk sets (prefix cumulative_logsumexp)
#    - Breslow tie handling
# =========================
@tf.function
def neg_log_partial_lik(y_true, y_pred):
    event = tf.cast(y_true[:, 0], tf.float32)
    time  = tf.cast(y_true[:, 1], tf.float32)
    risk  = tf.cast(tf.squeeze(y_pred, axis=-1), tf.float32)  # log-risk

    # sort by time descending
    order = tf.argsort(time, direction="DESCENDING")
    time  = tf.gather(time,  order)
    event = tf.gather(event, order)
    risk  = tf.gather(risk,  order)

    # prefix denominators: log(sum_{j<=i} exp(risk_j))
    lse_prefix = tf.math.cumulative_logsumexp(risk)

    # tie groups
    is_new = tf.concat([[True], tf.not_equal(time[1:], time[:-1])], axis=0)
    gid = tf.cumsum(tf.cast(is_new, tf.int32)) - 1

    is_end = tf.concat([tf.not_equal(time[:-1], time[1:]), [True]], axis=0)
    end_lse = tf.boolean_mask(lse_prefix, is_end)
    denom = tf.gather(end_lse, gid)

    loglik = tf.reduce_sum(event * (risk - denom))
    return -loglik / (tf.reduce_sum(event) + 1e-8)

# =========================
# 4) Train BNN correctly:
#    - FULL BATCH (Cox loss needs full risk sets)
#    - shuffle=False
# =========================
def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te, lr=1e-3, epochs=100):
    model = build_bnn(X_tr.shape[1])
    model.compile(optimizer=keras.optimizers.RMSprop(lr), loss=neg_log_partial_lik)

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    es = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
    timer = EpochTimer()

    model.fit(
        X_tr.astype(np.float32),
        y_tr,
        batch_size=X_tr.shape[0],   # FULL BATCH (critical)
        epochs=epochs,
        verbose=0,
        validation_split=0.2,       # ok if it still contains events; otherwise do manual split
        shuffle=False,
        callbacks=[es, timer]
    )

    g_tr = model.predict(X_tr.astype(np.float32), verbose=0).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), verbose=0).reshape(-1)
    return g_tr, g_te

# ============================================================
# 5) END-TO-END: from df_processed -> X,T,E -> split -> train
# ============================================================

# (A) Ensure your df_processed already has:
#     - num__DURATION (float days)  <-- must be computed and > 0
#     - num__Event (0/1)
#     - all encoded covariates including SECTION_FREQ
# and the date__* columns exist but will be dropped from X.

# --- filter out bad times (this fixes your Min T: nan) ---
dfv = df_processed.copy()
dfv = dfv[dfv["num__DURATION"].notna()].copy()
dfv = dfv[dfv["num__DURATION"] > 0].copy()   # survival time must be strictly positive
dfv = dfv[dfv["num__Event"].notna()].copy()

# --- build T,E ---
T = dfv["num__DURATION"].to_numpy(np.float32)
E = dfv["num__Event"].astype(int).to_numpy(np.int32)

# --- build X (keep SECTION_FREQ; drop leakage/date) ---
drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP",
]
X_df = dfv.drop(columns=drop_cols, errors="ignore")
X = X_df.to_numpy(np.float32)

# --- sanity ---
print("NaNs in T:", np.isnan(T).sum())
print("Min T:", float(np.nanmin(T)))
assert np.isnan(T).sum() == 0
assert float(np.min(T)) > 0

# --- stratified split ---
X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X, T, E, test_size=0.2, random_state=42, stratify=E
)

print("Train events:", int(y_event_tr.sum()))
print("Test events:", int(y_event_te.sum()))

# --- scale features for BNN stability ---
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train).astype(np.float32)
X_test_s  = scaler.transform(X_test).astype(np.float32)

# --- train BNN nonlinear term g(x) ---
g_tr, g_te = train_bnn_and_get_g(
    X_train_s, y_time_tr, y_event_tr, X_test_s, lr=1e-3, epochs=100
)

# ============================================================
# 6) HYBRID LINEAR COX on (AXLE_LOAD, GMTCARRIED, g_bnn)
# ============================================================

# Find indices of linear columns inside X_df columns
# (Your encoded names are like ord__AXLELOAD and num__GMTCARRIED)
colnames = list(X_df.columns)
def find_col(name_substr):
    hits = [i for i, c in enumerate(colnames) if name_substr in c]
    if len(hits) != 1:
        raise ValueError(f"Expected 1 match for {name_substr}, got {len(hits)}: {[colnames[i] for i in hits[:10]]}")
    return hits[0]

i_axle     = find_col("AXLELOAD")
i_gmt      = find_col("GMTCARRIED")
i_annual   = find_col("ANNUAL_GMT")
i_rail     = find_col("RAIL_SECTION")
i_service  = find_col("SERVICE_LIFE")
i_speed    = find_col("SPEED")

# OHE columns
i_track_lwr = find_col("TRACK_TYPE_LWR")
i_track_swr = find_col("TRACK_TYPE_SWR")
i_straight  = find_col("STRAIGHT_CURVE_STRAIGHT")

X_lin_tr = X_train[:, [i_axle,i_gmt,i_annual,i_rail,i_service,i_speed,i_track_lwr,i_track_swr,i_straight]]
X_lin_te = X_test[:,  [i_axle,i_gmt,i_annual,i_rail,i_service,i_speed,i_track_lwr,i_track_swr,i_straight]]

train_df = pd.DataFrame({
    "time": y_time_tr,
    "event": y_event_tr,
    "AXLE_LOAD": X_lin_tr[:,0],
    "GMT_CARRIED": X_lin_tr[:,1],
    "ANNUAL_GMT": X_lin_tr[:,2],
    "RAIL_SECTION": X_lin_tr[:,3],
    "SERVICE_LIFE": X_lin_tr[:,4],
    "SPEED": X_lin_tr[:,5],
    "TRACK_TYPE_LWR": X_lin_tr[:,6],
    "TRACK_TYPE_SWR": X_lin_tr[:,7],
    "STRAIGHT_CURVE_STRAIGHT": X_lin_tr[:,8],
    "g_bnn": g_tr
})

test_df = pd.DataFrame({
    "time": y_time_te,
    "event": y_event_te,
    "AXLE_LOAD": X_lin_te[:,0],
    "GMT_CARRIED": X_lin_te[:,1],
    "ANNUAL_GMT": X_lin_te[:,2],
    "RAIL_SECTION": X_lin_te[:,3],
    "SERVICE_LIFE": X_lin_te[:,4],
    "SPEED": X_lin_te[:,5],
    "TRACK_TYPE_LWR": X_lin_te[:,6],
    "TRACK_TYPE_SWR": X_lin_te[:,7],
    "STRAIGHT_CURVE_STRAIGHT": X_lin_te[:,8],
    "g_bnn": g_te
})

formula = """
AXLE_LOAD + GMT_CARRIED + ANNUAL_GMT + RAIL_SECTION +
SERVICE_LIFE + SPEED + TRACK_TYPE_LWR + TRACK_TYPE_SWR +
STRAIGHT_CURVE_STRAIGHT + g_bnn
"""



cph = CoxPHFitter()
cph.fit(train_df, duration_col="time", event_col="event",
        formula=formula)

print(cph.params_)

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(train_df["time"].values, -risk_tr, train_df["event"].values)
c_te = concordance_index(test_df["time"].values, -risk_te, test_df["event"].values)
print(f"C-index train={c_tr:.3f}  test={c_te:.3f}")

NaNs in T: 0
Min T: 1.0
Train events: 440
Test events: 110

/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:99: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  loc = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tensorflow_probability/python/layers/util.py:109: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use the `layer.add_weight()` method instead.
  untransformed_scale = add_variable_fn(
/usr/local/lib/python3.12/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(

Training started...

Epoch 001 | loss=4.9476 | val_loss=3.5909 | epoch_time=3.14s | total_time=0.05 min
Epoch 002 | loss=4.9569 | val_loss=3.6232 | epoch_time=0.04s | total_time=0.05 min
Epoch 003 | loss=4.9404 | val_loss=3.5830 | epoch_time=0.04s | total_time=0.05 min
Epoch 004 | loss=4.9908 | val_loss=3.5682 | epoch_time=0.05s | total_time=0.05 min
Epoch 005 | loss=4.9553 | val_loss=3.5285 | epoch_time=0.05s | total_time=0.06 min
Epoch 006 | loss=4.9501 | val_loss=3.5984 | epoch_time=0.05s | total_time=0.06 min
Epoch 007 | loss=4.9317 | val_loss=3.6075 | epoch_time=0.04s | total_time=0.06 min
Epoch 008 | loss=4.9630 | val_loss=3.6252 | epoch_time=0.03s | total_time=0.06 min
Epoch 009 | loss=4.9676 | val_loss=3.5817 | epoch_time=0.04s | total_time=0.06 min
Epoch 010 | loss=4.9609 | val_loss=3.5978 | epoch_time=0.04s | total_time=0.06 min
Epoch 011 | loss=4.9572 | val_loss=3.5759 | epoch_time=0.04s | total_time=0.06 min
Epoch 012 | loss=4.9505 | val_loss=3.6113 | epoch_time=0.04s | total_time=0.06 min
Epoch 013 | loss=4.9653 | val_loss=3.5910 | epoch_time=0.04s | total_time=0.06 min
Epoch 014 | loss=4.9463 | val_loss=3.5712 | epoch_time=0.04s | total_time=0.06 min
Epoch 015 | loss=4.9254 | val_loss=3.5740 | epoch_time=0.04s | total_time=0.06 min

Training finished in 0.06 minutes.

covariate
AXLE_LOAD                 -0.022003
GMT_CARRIED               -0.010946
ANNUAL_GMT                 0.097140
RAIL_SECTION              -5.058756
SERVICE_LIFE               0.020427
SPEED                      0.009158
TRACK_TYPE_LWR             0.366820
TRACK_TYPE_SWR             0.571747
STRAIGHT_CURVE_STRAIGHT   -0.352874
g_bnn                     -0.072263
Name: coef, dtype: float64
C-index train=0.917  test=0.911

In [ ]:
import numpy as np

# --- predicted survival curves for test set ---
# choose a grid within test follow-up, strictly inside max
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)  # strictly less than max
times = np.linspace(t_min, eps, 200)

surv_df = cph.predict_survival_function(test_df, times=times)  # shape: (len(times), n_test)

# --- predicted median survival time per sample ---
S = surv_df.to_numpy().T  # (n_test, n_times)

def median_time_from_curve(times, s_row):
    # first time S(t) <= 0.5; if never crosses, return max time
    idx = np.where(s_row <= 0.5)[0]
    return times[idx[0]] if len(idx) else times[-1]

t50_pred = np.array([median_time_from_curve(times, s_row) for s_row in S], dtype=float)

# --- RMSE on events only ---
mask_event = (y_event_te == 1)
rmse_t50 = np.sqrt(np.mean((t50_pred[mask_event] - y_time_te[mask_event]) ** 2))

print("RMSE (median survival time, events only):", rmse_t50)
print("Num events used:", int(mask_event.sum()))

RMSE (median survival time, events only): 51.79159126899807
Num events used: 110

In [ ]:
!pip install scikit-survival

Collecting scikit-survival
  Downloading scikit_survival-0.27.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (7.0 kB)
Collecting ecos (from scikit-survival)
  Downloading ecos-2.0.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.5.3)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.14.1)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.0.2)
Requirement already satisfied: osqp>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.1.1)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (2.2.2)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from scikit-survival) (1.16.3)
Collecting scikit-learn<1.9,>=1.8.0 (from scikit-survival)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from osqp>=1.0.2->scikit-survival) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from osqp>=1.0.2->scikit-survival) (75.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->scikit-survival) (2025.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.9,>=1.8.0->scikit-survival) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->scikit-survival) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->osqp>=1.0.2->scikit-survival) (3.0.3)
Downloading scikit_survival-0.27.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 52.1 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 121.6 MB/s eta 0:00:00
Downloading ecos-2.0.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (222 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.1/222.1 kB 26.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn, ecos, scikit-survival
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed ecos-2.0.14 scikit-learn-1.8.0 scikit-survival-0.27.0

In [ ]:
from sksurv.metrics import integrated_brier_score
from sksurv.util import Surv

# structured arrays
y_train_struct = Surv.from_arrays(y_event_tr.astype(bool), y_time_tr.astype(float))
y_test_struct  = Surv.from_arrays(y_event_te.astype(bool), y_time_te.astype(float))

# times must be within [min(test); max(test)) strictly
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)
times_ibs = np.linspace(t_min, eps, 200)

# survival predictions matrix: (n_test, n_times)
surv_df_ibs = cph.predict_survival_function(test_df, times=times_ibs)
S_pred = surv_df_ibs.to_numpy().T  # (n_test, n_times)

ibs = integrated_brier_score(
    y_train_struct,
    y_test_struct,
    S_pred,
    times_ibs
)

print("IBS:", float(ibs))

IBS: 0.009733138365318918